services:
  admin-web:
    build: ./frontend/admin-web
    ports:
      - "4000:80"
    networks:
      - capitalflow-net

  user-web:
    build: ./frontend/user-web
    ports:
      - "3010:3010"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    networks:
      - capitalflow-net

networks:
  capitalflow-net:
