"""Xuất Alembic baseline tự chứa từ schema SQL Server đang vận hành.

Vai trò: phản chiếu 17 bảng ORM từ database thật và render thành revision cố định.
Đầu vào: ``DATABASE_URL``/cấu hình API, revision ID và đường dẫn đầu ra.
Đầu ra: một revision Alembic chỉ chứa schema, không chứa dữ liệu người dùng.
Ràng buộc an toàn: chỉ đọc metadata; từ chối ghi đè file baseline đã tồn tại.
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from alembic.autogenerate.api import render_python_code
from alembic.operations import ops
from sqlalchemy import CheckConstraint, MetaData, create_engine, text
from sqlalchemy.pool import NullPool


DATABASE_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = DATABASE_ROOT.parent
API_ROOT = REPOSITORY_ROOT / "capitalflow-api"
LEGACY_MARKER = "da10f25d5743"
sys.path.insert(0, str(API_ROOT))

import app.models  # noqa: E402,F401
from app.core.config import settings  # noqa: E402
from app.models.base import Base  # noqa: E402


def render_baseline(revision: str) -> str:
    """Phản chiếu schema live và tạo nội dung revision không phụ thuộc model sau này."""

    url = os.environ.get("DATABASE_URL", settings.database_url)
    engine = create_engine(url, poolclass=NullPool, hide_parameters=True)
    live_metadata = MetaData()
    application_tables = sorted(Base.metadata.tables)

    # Chỉ phản chiếu đúng các bảng nghiệp vụ; không xuất dữ liệu hoặc bảng version.
    with engine.connect() as connection:
        live_metadata.reflect(bind=connection, only=application_tables)

        # Dialect SQL Server hiện không phản chiếu CHECK constraint qua Inspector.
        # Bổ sung chúng từ system catalog để baseline không làm yếu invariant dữ liệu.
        for table_name, constraint_name, definition in connection.execute(
            text(
                "SELECT t.name, cc.name, cc.definition "
                "FROM sys.check_constraints cc "
                "JOIN sys.tables t ON t.object_id=cc.parent_object_id "
                "WHERE t.name IN (SELECT value FROM STRING_SPLIT(:tables, ',')) "
                "ORDER BY t.name, cc.name"
            ),
            {"tables": ",".join(application_tables)},
        ):
            live_metadata.tables[table_name].append_constraint(
                CheckConstraint(definition, name=constraint_name)
            )

    missing = sorted(set(application_tables) - set(live_metadata.tables))
    if missing:
        raise RuntimeError(f"Database thiếu bảng ORM: {', '.join(missing)}")

    upgrade_operations: list[ops.MigrateOperation] = []
    for table in live_metadata.sorted_tables:
        upgrade_operations.append(ops.CreateTableOp.from_table(table))
        for index in sorted(table.indexes, key=lambda item: item.name or ""):
            upgrade_operations.append(ops.CreateIndexOp.from_index(index))

    # Downgrade baseline chỉ dành cho CSDL kiểm chứng trống; không tự chạy production.
    downgrade_operations: list[ops.MigrateOperation] = []
    for operation in reversed(upgrade_operations):
        downgrade_operations.append(operation.reverse())

    upgrade_code = render_python_code(ops.UpgradeOps(upgrade_operations))
    downgrade_code = render_python_code(ops.DowngradeOps(downgrade_operations))
    upgrade_code = upgrade_code.replace(
        "# ### commands auto generated by Alembic - please adjust! ###",
        "    # ### Các lệnh schema được Alembic sinh từ database thật và đã kiểm chứng. ###",
    ).replace(
        "    # ### end Alembic commands ###",
        "    # ### Kết thúc phần lệnh dựng schema. ###",
    )
    downgrade_code = downgrade_code.replace(
        "# ### commands auto generated by Alembic - please adjust! ###",
        "    # ### Các lệnh hạ baseline chỉ dành cho database kiểm chứng được phép xóa. ###",
    ).replace(
        "    # ### end Alembic commands ###",
        "    # ### Kết thúc phần lệnh hạ schema. ###",
    )
    created = datetime.now(timezone.utc).isoformat()

    return f'''"""Baseline đầy đủ phản chiếu từ SQL Server đang vận hành.

Revision ID: {revision}
Revises: {LEGACY_MARKER}
Ngày tạo UTC: {created}

Revision này chỉ chứa schema của 17 bảng nghiệp vụ, không chứa dữ liệu người dùng.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql


revision: str = "{revision}"
down_revision: Union[str, Sequence[str], None] = "{LEGACY_MARKER}"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Dựng schema CapitalFlow đầy đủ trên database trống."""

{upgrade_code}


def downgrade() -> None:
    """Chỉ hạ baseline trên database kiểm chứng đã được phép xóa."""

{downgrade_code}
'''


def main() -> None:
    """Phân tích tham số và ghi baseline mới theo cơ chế không ghi đè."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--revision", default="cfdb_20260924_baseline")
    parser.add_argument(
        "--output",
        type=Path,
        default=DATABASE_ROOT / "alembic" / "versions" / "cfdb_20260924_baseline.py",
    )
    args = parser.parse_args()

    output = args.output.resolve()
    if output.exists():
        raise FileExistsError(f"Từ chối ghi đè baseline: {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_baseline(args.revision), encoding="utf-8", newline="\n")
    print(f"BASELINE_CREATED={output}")


if __name__ == "__main__":
    main()
